accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('logout/', views.signout, name='logout')
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('accounts/', include('accounts.urls'))  # account 추가
]

todo/urls.py
from django.urls import path
from todo.views import TodoCreate, delete_todo, index, todos, update_todo, complete_todo

urlpatterns = [
	path('', todos, name="todo_list"),
	path('index/', index),
	path('create_todo/', TodoCreate.as_view(), name="create"),
	path('update_todo/<int:pk>/', update_todo, name='update'),
	path('delete_todo/<int:pk>/', delete_todo, name='delete'),
	path('complete_todo/<int:pk>/', complete_todo, name='complete'),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import(
    AbstractBaseUser, BaseUserManager, AbstractUser
)

class UserManager(BaseUserManager):
    def create_user(self, email, password, staff=False, admin=False, active=True):
        if not email:
            raise ValueError('이메일을 입력 해주세요')
        if not password:
            raise ValueError('비밀번호를 입력해주세요')
        user = self.model(email = self.normalize_email(email))
        user.set_password(password)
        user.staff = staff
        user.admin = admin
        user.active = active
        user.save(using=self._db)
        
        return user
    
    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password,
            staff = True,
            admin = True
        )
        return user

class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    nickname = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True) # 로그인 할 수 있나? (휴면 계정이 아닌가?)
    staff = models.BooleanField(default=False) # superuser가 아닌 staff
    admin = models.BooleanField(default=False) # superuser
    
    USERNAME_FIELD = 'email' # username을 email로 사용하겠다. 
    REQUIRED_FIELDS = []
    
    objects = UserManager()
    
    def __str__(self):
        return self.email
    
    @property
    def is_staff(self):
        return self.staff
    
    @property
    def is_superuser(self):
        return self.admin
    
    def has_perm(self, perm, obj=None):
        return self.admin
    
    def has_module_perms(self, app_label):
        return self.admin
    

todo/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
	todo = models.CharField(max_length=30)
	description = models.TextField()
	important = models.BooleanField(default=False)
	complete = models.BooleanField(default=False)

	def __str__(self):
		return f'{self.todo} [{self.id}]'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):  # 회원가입 폼
    email = forms.EmailField(
        max_length=255,
        help_text='Enter a valid email address',
    )
    nickname = forms.CharField(
        max_length=255,
        help_text='Enter a valid nickname',
        required=True
    )
    password1=forms.CharField(
        label='Password',
        widget=forms.PasswordInput(),
        help_text='Your password mush contain at least 8 characters',
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput(),
        help_text='Enter the same password as before, for verification',
    )
    class Meta:
        model = User
        fields = ['email', 'nickname', 'password1', 'password2']
        
class SignInForm(AuthenticationForm):  # 로그인 폼
    class Meta:
        model = User
        fields = ['email', 'password']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import SignInForm, SignUpForm       # .forms 경로에서 작성한 폼을 불러옴
from django.contrib import messages

# Create your views here.
def signup(request):
    if request.method == 'GET':
        form = SignUpForm()
    elif request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('signin')
        
    return render(request, 'accounts/signup.html', {'form':form})
    
def signin(request):
    if request.method == 'GET':
        form = SignInForm()
    elif request.method == 'POST':
        form = SignInForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('todo_list')
            else:
                messages.error(request)
                
    return render(request, 'accounts/signin.html', {'form':form})

def signout(request):
    logout(request)
    return redirect('signin')

todo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from todo.models import TodoList
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def complete_todo(request, pk):
    comTodo = get_object_or_404(TodoList, pk=pk)
    comTodo.complete = True
    comTodo.save()
    return redirect('toods')

def delete_todo(request, pk):
	delTodo = get_object_or_404(TodoList, pk=pk)
	delTodo.delete()
	return redirect('todos')

def update_todo(request, pk):
	curTodo = get_object_or_404(TodoList, pk=pk)
	if request.method == 'POST':
		curTodo.todo = request.POST['todo']
		curTodo.description = request.POST['description']
		curTodo.important = request.POST.get('important') == "on"
		curTodo.complete = request.POST.get('complete') == "on"
		curTodo.save()
		return redirect('todos')
	return render(
		request,
		'todo/todo_update.html',
		{
			'curTodo': curTodo,
		},
	)
 
# def create_todo(request):
# 	myTodo = TodoList()
# 	if request.method == 'POST':
# 		myTodo.todo = request.POST['todo']
# 		myTodo.description = request.POST['description']
# 		myTodo.important = request.POST.get('important') == "on"
# 		myTodo.complete = request.POST.get('complete') == "on"
# 		myTodo.save()
# 		return redirect('todos')
# 	return render(
# 		request,
# 		'todo/todo_create.html'
# 	)

class TodoCreate(LoginRequiredMixin, CreateView):
    model = TodoList
    fields = ['todo', 'description', 'important']
    login_url = '/accounts/signin/'
    template_name = 'todo/todo_create.html'  # 템플릿 파일 이름 변경
    
    
def todos(request):
	todolist = TodoList.objects.all()
	return render(
		request,
		'todo/todos.html',
  		{
			'todolist': todolist,
			}
	)

def index(request):
	#todolist의 모든 레코드를 가져온다.
	todolist = TodoList.objects.all()
	return render(
		request,
		'todo/index.html',
		{
			#HTML에서 todolist라는 이름으로 todolist를 넘겨준다.
			'todolist': todolist,
		}
	)

accounts/templates/accounts/signin.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign In</title>
</head>
<body>
    <h2>Sign In (로그인)</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Sign In</button>
    </form>
<bodt>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign In</title>
</head>
<body>
    <h2>Sign Up (로그아웃)</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Sign Up</button>
    </form>
<bodt>
</html>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>Todos</title>
</head>
<body>
	<h1>Todos</h1>
	{% for todo in todolist %}
	<hr/>
	<h3> {{ todo.todo }}</h3>
	<p>{{ todo.description }}</p>
	<p>important : {{ todo.important }}</p>
	<p>complete : {{ todo.complete }}</p>
	{% endfor %}
</body>
</html>

todo/templates/todo/todo_create.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>Create Todo</title>
	<link rel="stylesheet" href="{% static 'todo/bootstrap/bootstrap.min.css' %}">
</head>
<body>
	<h1>Create New Todos</h1>
	<hr/>
	<form method='post' enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tbody>
				<tr>
					<th><label for="id_todo">Todo:</label></th>
					<td><input type="text" name="todo" maxlength="30" required="" id="id_todo"></td>
				</tr>
				<tr>
					<th><label for="id_description">Description:</label></th>
					<td><textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea></td>
				</tr>
				<tr>
					<th><label for="id_important">Important:</label></th>
					<td><input type="checkbox" name="important" id="id_important"></td>
				</tr>
				<tr>
					<th><label for="id_complete">Complete:</label></th>
					<td><input type="checkbox" name="complete" id="id_complete" ></td>
				</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-primary" style="margin-left: 350px;">Submit</button>
	</form>
</body>
</html>

todo/templates/todo/todo_update.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>Create Todo</title>
	<link rel="stylesheet" href="{% static 'todo/bootstrap/bootstrap.min.css' %}">
</head>
<body>
	<h1>Create New Todos</h1>
	<hr/>
	<form method='post' enctype="multipart/form-data">
		{% csrf_token %}
		<table>
			<tbody>
				<tr>
					<th><label for="id_todo">Todo:</label></th>
					<td><input type="text" name="todo" maxlength="30" required="" id="id_todo" value="{{ curTodo.todo }}"></td>
				</tr>
				<tr>
					<th><label for="id_description">Description:</label></th>
					<td><textarea name="description" cols="40" rows="10" required="" id="id_description">{{ curTodo.description }}</textarea></td>
				</tr>
				<tr>
					<th><label for="id_important">Important:</label></th>
					{% if curTodo.important %}
					<td><input type="checkbox" name="important" id="id_important" checked></td>
					{% else %}
					<td><input type="checkbox" name="important" id="id_important"></td>
					{% endif %}
				</tr>
				<tr>
					<th><label for="id_complete">Complete:</label></th>
					{% if curTodo.complete %}
					<td><input type="checkbox" name="complete" id="id_complete" checked></td>
					{% else %}
					<td><input type="checkbox" name="complete" id="id_complete"></td>
					{% endif %}
				</tr>
			</tbody>
		</table>
		<button type="submit" class="btn btn-primary" style="margin-left: 350px;">Submit</button>
	</form>
</body>
</html>

todo/templates/todo/todos.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>ToDo List Demo</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'todo/bootstrap/bootstrap.min.css' %}">
</head>
<body>
{% if user.is_authenticated %}
	<a href="/accounts/logout" class"btn btn-primary">Logout</a>
{% else %}
	<a href="/accounts/signup" class="btn btn-primary">회원가입</a>
	<a href="/accounts/signin" class="btn btn-primary">Login</a>
{% endif %}

<section class="vh-100" style="background-color: #eee;">
<div class="container py-5 h-100">
	<div class="row d-flex justify-content-center align-items-center h-100">
		<div class="col-md-12 col-xl-10">
			<div class="card">
				<div class="card-header p-3">
					<h5 class="mb-0"><i class="fa-solid fa-list-check"></i>&nbsp;ToDo List</h5>
				</div>
				<div class="card-body overflow-auto" style="position: relative; height: 400px">
					<table class="table mb-0">
						<thead>
							<tr>
							<th>ToDo</th>
							<th>Description</th>
							<th>Update</th>
							<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for todo in todolist %}
							{% if todo.complete != True %}
							<tr class="fw-normal">
							<th>
								{% if todo.important %}
								<i class="fa-solid fa-star text-warning"></i>
								{% else %}
								<i class="fa-solid fa-star"></i>
								{% endif %}
								<span class="ms-2">{{ todo.todo }}</span>
							</th>
							<td class="align-middle">
								<span>{{ todo.description }}</span>
							</td>
							<td class="align-middle">
								<h5 class="mb-0"><a href="{% url 'update' todo.pk %}" role="button" class="badge bg-secondary" style="text-decoration-line: none;">수정하기</a></h6>
							</td>
							<td class="align-middle">
								<a href="{% url 'complete' todo.pk %}" data-bs-toggle="tooltip" data-bs-title="Done"><i class="fa-solid fa-check text-success me-3"></i></a>
								<a href="{% url 'delete' todo.pk %}" data-bs-toggle="tooltip" data-bs-title="Remove"><i class="fa-solid fa-trash-can text-danger"></i></a>
							</td>
							</tr>
							{% endif%}
							{% endfor %}
						</tbody>
					</table>
				</div>
				<div class="card-footer text-end p-3">
					<a href="{% url 'create'%}" class="btn btn-primary">Add Task</a>
				</div>
			</div>
		</div>
	</div>
</div>
</section>
<script src="https://kit.fontawesome.com/6347866849.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script>
	const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
	const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
</body>
</html>